### ISSUE TITLE
Change user location

### ISSUE THREAD

**Issue by VK3AWA** [ianrenton/field-spotter#42]
Is it possible to enter the location of the user? At the moment "you" is in the UK and I would like to have it centered on my location in Australia.

THANKS Daryl - VK3AWA

**Comment by ianrenton** [comment]
Hi,

I will admit the default view is pretty UK centric, but I assume most people don't see it for long - geolocation should kick in after a few seconds and pan your view to where you are, adding a marker as well.

Did you reject the location permission on purpose? If you'd prefer a manual entry for location, I can definitely offer that as an option.

If not, it could be that geolocation isn't working for you for some reason - if so could you please give me some details of your device, browser, installed as a PWA or not, etc?

Thanks

Ian

**Comment by VK3AWA** [comment]
Hi Ian,
THANKS for the prompt reply. 

OK, on further investigation, the following browsers do not auto locate my QTH - Duck Duck Go, Firefox and Microsoft Edge.  Only Google Chrome works .  I am running the App on my Win11 PC.

Cheers Daryl

**Comment by ianrenton** [comment]
Thanks, I'll look into it. I have had the same problem on Firefox too, but I wasn't sure if it was just me, just an issue on Linux, etc. so at least now I know it's a common problem!

I'll see if I can find a proper solution, if not, I'll add the ability to set your location manually.

**Comment by VK3AWA** [comment]
THANKS Ian.  Love the program.

**Comment by ianrenton** [comment]
I have this problem generally across any sites that try to use browser location in Firefox, so I don't think it's a problem specific to Field Spotter. I can't really therefore "fix" it.

However, I have added geo-IP lookup as a fallback to the device/browser location, which should get it approximately right.

I have also added the ability to override both of the above with a manually set location, either by entering lat/long (in the Display menu) or by dragging the grey marker if it appears.

Hope that helps, please let me know (and re-open this issue) if you have problems or would prefer a different solution.
